Repository Savital/BookShopTMD, pull requests merged in 2019-04, with the labels that each got.

#14 Dev
  .travis.yml
  BookShop/admin.py
  BookShop/models.py
  BookShopTMD/settings.py
  BookShopTMD/urls.py
  requirements.txt
  test_unit_pytest.py
Labels: help wanted

#16 Dev
  wiki-source/Registration.png
  wiki-source/admin_in.png
  wiki-source/login.png
Labels: bug

#19 Dev
  BookShop/admin.py
  BookShop/models.py
  BookShop/urls.py
  BookShopTMD/BookShopTMD/__init__.py
  BookShopTMD/BookShopTMD/settings.py
  BookShopTMD/BookShopTMD/urls.py
  BookShopTMD/BookShopTMD/wsgi.py
  BookShopTMD/manage.py
  BookShopTMD/settings.py
  BookShopTMD/urls.py
  BookShopTMD/wsgi.py
  manage.py
Labels: enhancement

#21 Dev
  BookShop/admin.py
Labels: enhancement

#24 Dev
  BookShopTMD/settings.py
  wiki-source/Contacts.png
  wiki-source/administration.png
  wiki-source/main_window.png
  wiki-source/products.png
Labels: invalid

#25 Added some files for wiki
  wiki-source/1a.jpg
  wiki-source/1b.jpg
  wiki-source/1c.jpg
  wiki-source/1d.jpg
  wiki-source/3a.jpg
  wiki-source/3b.jpg
  wiki-source/ER-models.jpg
  wiki-source/architecture.png
Labels: duplicate

#31 Dev
  .travis.yml
  BookShop/models.py
  BookShop/tests.py
  BookShop/urls.py
  BookShop/views.py
  BookShopTMD/settings.py
  BookShopTMD/urls.py
Labels: enhancement, question

#35 Dev
  .travis.yml
  BookShop/models.py
  BookShop/urls.py
  BookShop/views.py
  templates/hello.html
  templates/login.html
  templates/product.html
  templates/register.html
Labels: enhancement, help wanted

#36 Dev
  templates/contact.html
  templates/home.html
Labels: duplicate

#37 Update README.md
  README.md
Labels: duplicate

#39 Dev
  static/images/book_front_picture.jpg
  static/images/no_image.jpg
  static/js/bootstrap.js
  static/js/bootstrap.min.js
  static/styles/bootstrap_css/bootstrap-grid.css
  static/styles/bootstrap_css/bootstrap-grid.css.map
  static/styles/bootstrap_css/bootstrap-grid.min.css
  static/styles/bootstrap_css/bootstrap-grid.min.css.map
  static/styles/bootstrap_css/bootstrap-reboot.css
  static/styles/bootstrap_css/bootstrap-reboot.css.map
  static/styles/bootstrap_css/bootstrap-reboot.min.css
  static/styles/bootstrap_css/bootstrap-reboot.min.css.map
  static/styles/bootstrap_css/bootstrap.css
  static/styles/bootstrap_css/bootstrap.css.map
  static/styles/bootstrap_css/bootstrap.min.css
  static/styles/bootstrap_css/bootstrap.min.css.map
  static/styles/font-awesome.css
  static/styles/font-awesome.min.css
  static/styles/fonts/FontAwesome.otf
  static/styles/fonts/fontawesome-webfont.eot
  static/styles/fonts/fontawesome-webfont.svg
  static/styles/fonts/fontawesome-webfont.ttf
  static/styles/fonts/fontawesome-webfont.woff
  static/styles/fonts/fontawesome-webfont.woff2
  static/styles/style.css
Labels: duplicate

#40 Dev
  .travis.yml
  BookShop/admin.py
  BookShop/models.py
  BookShop/tests.py
  BookShop/urls.py
  BookShop/views.py
  BookShopTMD/settings.py
  BookShopTMD/urls.py
  test_unit_pytest.py
Labels: duplicate

#43 Edited with doxygen and linter
  .travis.yml
  BookShop/models.py
  BookShop/urls.py
  BookShop/views.py
  Doxyfile
  README.md
Labels: wontfix
